### ISSUE TITLE
IndexError: index 2 is out of bounds for dimension 0 with size 2

### ISSUE THREAD

**Issue by WillyPKU** [cheerss/PixelLink-with-pytorch#1]
hello, 
Thanks for your sharing, I modify your code to complete my task based on pytorch. After  fininshed my training process to test, it appears an error which is "IndexError: index 2 is out of bounds for dimension 0 with size 2"
 Traceback (most recent call last):
  File "main.py", line 184, in <module>
    test_model()
  File "main.py", line 51, in test_model
    all_boxes = postprocess.mask_to_box(out_1, out_2)
  File "/home/liuchao/PixelLink-with-pytorch/postprocess.py", line 59, in mask_to_box
    link_neighbors[:, i] = link_neighbors[:, i] & pixel_class[i]
IndexError: index 2 is out of bounds for dimension 0 with size 2
I'm grateful for u to help me solve the error above,Thanks~

**Comment by cheerss** [comment]
aHa! You are right, there is a bug here, I have fixed it several days ago but I forgot to push the code. Actually, the size of pixel_class is [batch_size, 1, height, width], so I should squeeze it first and modify this line to link_neighbors[:, i] & pixel_class. I'll push it soon. 
By the way, the performance of the code is still not good enough for some strange reasons, I strongly recommend you to reference the code of the PixelLink's author.
